# Generated by Django 2.2.15 on 2020-09-04 12:42
from uuid import uuid4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plusforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedform',
            name='uuid',
            field=models.UUIDField(default=uuid4(), editable=False, unique=True),
            preserve_default=False,
        ),
    ]
