# Generated by Django 2.2.16 on 2020-11-11 15:43

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plusforms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedform',
            name='form',
        ),
        migrations.RemoveField(
            model_name='submittedform',
            name='id',
        ),
        migrations.AddField(
            model_name='submittedform',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AddField(
            model_name='submittedform',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submittedform',
            name='form_data',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='submittedform',
            name='meta_data',
            field=jsonfield.fields.JSONField(),
        ),
    ]
