# Generated by Django 2.2.24 on 2022-10-26 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plusforms', '0002_submittedform_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedform',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
