# Generated by Django 5.2 on 2025-05-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plusforms', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedform',
            name='email_to_verify',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='submittedform',
            name='is_processed',
            field=models.BooleanField(default=True),
        ),
    ]
